# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Bucket for storage
    boto_bucket: _env:S3_BUCKET

    # Amazon S3 Storage Configuration
    s3_bucket: _env:S3_BUCKET
    s3_encrypt: "_env:S3_ENCRYPT:true"
    s3_secure: "_env:S3_SECURE:true"

    # Set a random string here
    secret_key: _env:SECRET_KEY

prod:
    storage: s3
    storage_path: "_env:STORAGE_PATH:/"
    loglevel: _env:LOG_LEVEL

